name: Build Android APK with Capacitor

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/android-capacitor.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL || 'https://mybenzin.vercel.app' }}

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Capacitor CLI
        run: npm install -g @capacitor/cli

      - name: Add Android platform
        run: npx cap add android || echo "Android platform already exists"

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build Android APK
        run: cd android && ./gradlew assembleRelease
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}

      - name: Sign APK (optional)
        if: ${{ secrets.KEYSTORE_FILE && secrets.KEYSTORE_PASSWORD }}
        run: |
          echo "Signing APK..."
          # Add signing steps here if you have keystore

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: mybenzin-app
          path: android/app/build/outputs/apk/release/*.apk
          retention-days: 30

      - name: Upload AAB artifact (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mybenzin-bundle
          path: android/app/build/outputs/bundle/release/*.aab
          retention-days: 30
        continue-on-error: true

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: |
            android/app/build/outputs/apk/release/*.apk
            android/app/build/outputs/bundle/release/*.aab
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true