name: CI

on:
  workflow_dispatch:
    inputs:
      website_url:
        description: "URL вашего сайта (для TWA/Bubblewrap)"
        required: false
        default: "https://mybenzin.vercel.app"

jobs:
  web-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Run tests
        run: echo "Tests would run here"

  android-apk:
    runs-on: ubuntu-latest
    needs: web-ci

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Bubblewrap CLI
        run: npm i -g @bubblewrap/cli

      - name: Generate TWA project
        env:
          WEBSITE_URL: ${{ github.event.inputs.website_url || 'https://mybenzin.vercel.app' }}
        run: |
          echo "Using WEBSITE_URL=$WEBSITE_URL"
          
          mkdir -p twa-project
          cd twa-project
          
          cat > twa-manifest.json <<EOF
          {
            "packageId": "com.mybenzin.app",
            "host": "$WEBSITE_URL",
            "name": "Mybenzin",
            "launcherName": "Mybenzin",
            "display": "standalone",
            "themeColor": "#3B82F6",
            "navigationColor": "#1E40AF",
            "backgroundColor": "#FFFFFF",
            "enableNotifications": true,
            "startUrl": "/",
            "iconUrl": "$WEBSITE_URL/icon-512.png",
            "maskableIconUrl": "$WEBSITE_URL/icon-512.png",
            "splashScreenFadeOutDuration": 300,
            "signingKey": {
              "path": "./android.keystore",
              "alias": "android"
            },
            "appVersionName": "1.0.0",
            "appVersionCode": 1,
            "shortcuts": [],
            "generatorApp": "bubblewrap-cli",
            "webManifestUrl": "$WEBSITE_URL/manifest.json",
            "fallbackType": "customtabs",
            "features": {},
            "alphaDependencies": {
              "enabled": false
            },
            "enableSiteSettingsShortcut": true,
            "isChromeOSOnly": false,
            "isMetaQuest": false
          }
          EOF
          
          keytool -genkey -v -keystore android.keystore -alias android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US" -storepass android -keypass android

      - name: Check if icon exists
        env:
          WEBSITE_URL: ${{ github.event.inputs.website_url || 'https://mybenzin.vercel.app' }}
        continue-on-error: true
        run: |
          ICON_URL="$WEBSITE_URL/icon-512.png"
          if curl --output /dev/null --silent --head --fail "$ICON_URL"; then
            echo "✅ Icon exists: $ICON_URL"
          else
            echo "⚠️ Icon not found: $ICON_URL (continuing anyway)"
          fi

      - name: Initialize Bubblewrap project
        working-directory: twa-project
        run: |
          export CI=true
          echo "n" | bubblewrap init --manifest=./twa-manifest.json
          
          ls -la
          if [ -f "./gradlew" ]; then
            echo "✅ Project initialized successfully"
          else
            echo "❌ Project initialization failed"
            exit 1
          fi

      - name: Build TWA APK
        working-directory: twa-project
        run: |
          echo "Using JAVA_HOME: $JAVA_HOME"
          java -version
          
          chmod +x ./gradlew
          
          # Try release build first, fallback to debug
          ./gradlew assembleRelease --stacktrace || ./gradlew assembleDebug --stacktrace
          
          echo "Looking for APK files..."
          find . -name "*.apk" -type f

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: mybenzin-twa-apk
          path: |
            twa-project/app/build/outputs/apk/**/*.apk
          if-no-files-found: warn